#!/bin/sh
#
# eipen The daemon that setsup and destroys machines that the eipen-server has created
#
# chkconfig:   2345 20 80
# description: The daemon that setsup and destroys machines that the eipen-server has created
# processname: eipen-client

### BEGIN INIT INFO
# Provides: eipen
# Required-Start: $local_fs $network
# Required-Stop: $local_fs $network
# Default-Start: 2345
# Default-Stop: 016
# Short-Description: The daemon that cleans up sessions after the have expired
### END INIT INFO

# Source function library.
. /etc/rc.d/init.d/functions

exec="/usr/bin/eipen/eipen-client.py"
prog="eipen-client"
#config="<path to major config file>"

[ -e /etc/sysconfig/$prog ] && . /etc/sysconfig/$prog

lockfile=/var/lock/subsys/$prog
pidfile=/var/run/$prog.pid

setpidfile() {
    PID=`ps aux | grep $exec | grep -v grep | awk '{print $2}'`
    echo $PID > $pidfile
}

start() {
#    [ -x $exec ] || exit 5
#    [ -f $config ] || exit 6
    echo -n $"Starting $prog: "
    daemon /usr/bin/python $exec start
    retval=$?
    echo
    [ $retval -eq 0 ] && touch $lockfile
    setpidfile
    return $retval
}

stop() {
    echo -n $"Stopping $prog: "
    /usr/bin/python $exec stop
    retval=$?
    echo
    [ $retval -eq 0 ] && rm -f $lockfile && rm -f $pidfile
    return $retval
}

restart() {
    stop
    start
}

reload() {
    restart
}

force_reload() {
    restart
}

rh_status() {
    PID=`ps aux | grep $exec | grep -v grep | awk '{print $2}'`
    if [ "$PID" == "" ]
    then
       echo "$prog is not running"
       return -1
    else
       echo "$prog is running... ($PID)"
    fi

    return 0
}

rh_status_q() {
    rh_status >/dev/null 2>&1
}


case "$1" in
    start)
        rh_status_q && exit 0
        $1
        ;;
    stop)
        rh_status_q || exit 0
        $1
        ;;
    restart)
        $1
        ;;
    reload)
        rh_status_q || exit 7
        $1
        ;;
    force-reload)
        force_reload
        ;;
    status)
        rh_status
        ;;
    condrestart|try-restart)
        rh_status_q || exit 0
        restart
        ;;
    *)
        echo $"Usage: $0 {start|stop|status|restart|try-restart|reload|force-reload}"
        exit 2
esac
exit $?
